#!/usr/bin/env bash
#
# add this to crontab
# */1 * *  *  * /usr/local/bin/incoming /var/www/apt-repo/incoming
#

echo ""
echo "================ $(date) ================"
echo ""

source $HOME/.gpg-agent-info
export GPG_AGENT_INFO

INCOMING=$1
CODENAME=trusty

cd /var/www/apt-repo
found=0
for f in $INCOMING/*.deb; do
    if [ -e $f ]; then
        found=1
        break
    fi
done

if [[ $found == 0 ]]; then
    echo "Nothing to do"
    exit
fi

for f in $INCOMING/*.deb; do
    echo "Processing $f"
    echo reprepro --ask-passphrase -Vb . includedeb $CODENAME $f
    reprepro --ask-passphrase -Vb . includedeb $CODENAME $f
    retcode=$?
    if [[ $retcode != 0 ]]; then
        echo "Return code $retcode"
    else
        rm $f
    fi
    echo "Processing $f done"
done
echo "All done"
